
title: "Les histoires de Allal"
description: "Souvenirs de vie, récits et réflexions"
url: "https://elfilalimed23-jpg.github.io"
baseurl: "/Allal_blog"
lang: fr
timezone: Africa/Casablanca

# Thème moderne (GitHub Pages compatible)
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

# Plugins supportés par GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

# Apparence
minimal_mistakes_skin: "air"   # options: default, dark, air, sunrise, neon...
search: true
logo: "/Allal_blog/assets/images/avatar.png"

author:
  name: "Allal"
  avatar: "/Allal_blog/assets/images/avatar.png"
  bio: "Écrire pour transmettre."
  location: "Maroc"

# Pagination (facultatif, non bloquant si plugin absent)
paginate: 5
paginate_path: "/page:num/"

# Collections de pages
collections:
  pages:
    output: true
    permalink: /:name/

# Defaults (mise en page des posts et pages)
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# SEO
social:
  name: "Les histoires de Allal"
  links: []

# Flux
atom_feed:
  hide: false
